scripts:
  - name: Build Widget Extension & iOS App
    script: |
      # 1. Принудительно собираем таргет виджета
      cd ios
      xcodebuild -project Runner.xcodeproj \
                 -scheme WidgetExtension \
                 -configuration Release \
                 -sdk iphoneos \
                 CODE_SIGNING_ALLOWED=NO \
                 build
      cd ..

      # 2. Собираем и упаковываем итоговое приложение с виджетом
      flutter build ipa --release \
        --export-options-plist=$HOME/export_options.plist