platform :ios, '14.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Если Flutter передает плагины, CocoaPods их подтянет автоматически
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Принудительно ставим iOS 14.0 абсолютно для всех модулей и плагинов
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
